SELECT
  'Cap. SR: RIND.01 ' AS REZULTAT
FROM
  VW_DATA_ALL D
WHERE
  (D.PERIOADA = :PERIOADA) AND
  (D.CUIIO=:CUIIO ) AND
  (D.FORM = :FORM               ) AND

  D.FORM IN (33) 
  
HAVING
  
  SUM(CASE WHEN D.CAPITOL=1201 AND D.RIND IN('01') THEN NVAL(D.COL1) ELSE 0 END) > 0 
 
  
  