SELECT 
    D.CUIIO,
    D.RIND
  
  
  AS REZULTAT

FROM
  CIS2.VW_DATA_ALL D            
      
WHERE
  (D.PERIOADA IN (:PERIOADA ) AND
  (D.CUIIO=:CUIIO        ) AND
  (D.CUIIO_VERS=:CUIIO_VERS     OR :CUIIO_VERS = -1) AND
  (D.FORM = :FORM       ) AND
  (D.FORM_VERS=:FORM_VERS ) AND
  (D.CAPITOL=:CAPITOL           OR :CAPITOL = -1) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1) AND
  (D.ID_MD=:ID_MD               OR :ID_MD = -1) AND
  
  D.FORM IN (33)  AND
  D.CAPITOL IN (379) AND
  D.RIND IN ('1')
GROUP BY
  CC.NR_COLUMN
HAVING
    CIS2.NVAL(SUM(CASE WHEN D.PERIOADA IN (:PERIOADA) AND D.RIND IN('1') THEN DECODE(CC.NR_COLUMN, '1', D.COL1, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '8', D.COL8) ELSE 0 END)) <
    CIS2.NVAL(SUM(CASE WHEN D.PERIOADA IN (:PERIOADA - 1) AND D.RIND IN('1') THEN DECODE(CC.NR_COLUMN, '1', D.COL1, '3', D.COL3, '4', D.COL4, '5', D.COL5, '6', D.COL6, '8', D.COL8) ELSE 0 END))
  
