

WHERE
  D.PERIOADA IN (:pPERIOADA, :pPERIOADA-4) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (33) AND D.CAPITOl = 379
  AND D.RIND IN ('4')