SELECT 
D.CUIIO,
D.RIND,
SUM(D.COL4) AS COL4

FROM CIS2.VW_DATA_ALL D

WHERE
  D.PERIOADA IN (:pPERIOADA, :pPERIOADA-4) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (33) AND D.CAPITOl = 379
  AND D.RIND IN ('4')
  AND D.CUIIO = 819384
  
  GROUP BY
  D.CUIIO,
  D.RIND
  
  
  ORDER BY
  D.CUIIO,
  D.RIND
  