SELECT
  8 AS ORDINE, 
  'bovine' AS NUME_ROW,
  '-' AS NR_ROW,  
 -- ((tab.1.1 rd. 2 col.1 )*100000 / tab.1.1 rd.3 col.1) AP
  CIS2.NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('2') AND D.CAPITOL IN (379)THEN D.COL1 END))*100000/
  CIS2.NOZERO(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA-4) AND D.RIND IN ('3') AND D.CAPITOL IN (379) THEN D.COL1 END)) AS COL1,
  CIS2.NVAL(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('2') AND D.CAPITOL IN (379)THEN D.COL1 END))*100000/
  CIS2.NOZERO(SUM(CASE WHEN D.PERIOADA IN (:pPERIOADA) AND D.RIND IN ('3') AND D.CAPITOL IN (379) THEN D.COL1 END)) AS COL2
FROM 
  CIS2.VW_DATA_ALL D
WHERE
  D.PERIOADA IN (:pPERIOADA, :pPERIOADA-4) AND 
  D.FORM_VERS = :pFORM_VERS     AND    
  (:pID_MDTABLE=:pID_MDTABLE) AND
  D.CUATM_FULL LIKE '%'||:pCOD_CUATM||';%' AND
  D.FORM IN (33) AND
  D.RIND IN ('2','3') AND 
  D.CAPITOL IN (379)