SELECT   

D.RIND,
--D.ID_MD,
--MR.DENUMIRE,  
SUM(D.COL1) AS COL1,
SUM(D.COL2) AS COL2,
SUM(D.COL3) AS COL3,
SUM(D.COL4) AS COL4,
SUM(D.COL5) AS COL5,
SUM(D.COL6) AS COL6
   
 

FROM

  USER_EREPORTING.VW_DATA_ALL_FOR_VALIDATE  D
                INNER JOIN CIS2.MD_RIND MR ON MR.ID_MD = D.ID_MD


WHERE
   D.PERIOADA IN (:PERIOADA) AND
  
  (D.CUIIO=:CUIIO               ) AND
  (D.CUIIO_VERS=:CUIIO_VERS  OR :CUIIO_VERS = -1   ) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS       ) AND
  (D.CAPITOL=:CAPITOL OR :CAPITOL = - 1           ) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1 ) AND
  (D.ID_MD=:ID_MD OR :ID_MD = -1               ) AND
  

--   D.CUIIO = 819906 AND 
  
  D.FORM IN (33)  AND
  D.CAPITOL IN (379)
  AND  D.NUM IN (2,3,4)
 
 
GROUP BY 
D.RIND
--D.ID_MD,
--MR.DENUMIRE