SELECT 
'Rind '||L.RIND||':  COL6 - '||SUM(NVAL(L.COL6)) ||' <  '|| SUM(NVAL(R.COL6))  AS REZULTAT
FROM 
( 
SELECT 
L.RIND,
L.ID_MD,
L.DENUMIRE,
L.ORDINE,
SUM(R.COL6) AS COL6
 FROM 
(
 
SELECT  
        D.RIND,
        D.ID_MD,
        D.DENUMIRE,
        D.ORDINE 
                
            FROM CIS2.MD_RIND D 
            
            WHERE 
            D.CAPITOL = 379
AND D.STATUT = '1'
AND D.RIND_VERS = 1060





) L LEFT JOIN (

SELECT   

D.RIND,
D.ID_MD,
MR.DENUMIRE,  
SUM(D.COL1) AS COL1,
SUM(D.COL2) AS COL2,
SUM(D.COL3) AS COL3,
SUM(D.COL4) AS COL4,
SUM(D.COL5) AS COL5,
SUM(D.COL6) AS COL6,
SUM(D.COL8) AS COL8
   
 

FROM

  USER_EREPORTING.VW_DATA_ALL_FOR_VALIDATE  D
                INNER JOIN CIS2.MD_RIND MR ON MR.ID_MD = D.ID_MD


WHERE
   D.PERIOADA IN (:PERIOADA) AND
  
  (D.CUIIO=:CUIIO               ) AND
  (D.CUIIO_VERS=:CUIIO_VERS  OR :CUIIO_VERS = -1   ) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS       ) AND
  (D.CAPITOL=:CAPITOL OR :CAPITOL = - 1           ) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1 ) AND
  (D.ID_MD=:ID_MD               ) AND
  

   --D.CUIIO = 819906 AND 
  
  D.FORM IN (33)  AND
  D.CAPITOL IN (379)
  AND  D.NUM IN (2,3,4)
 
 
GROUP BY 
D.RIND,
D.ID_MD,
MR.DENUMIRE


) R ON R.RIND = L.RIND


GROUP BY 
L.RIND,
L.DENUMIRE,
L.ORDINE,
L.ID_MD

ORDER BY
L.ORDINE 



) L  LEFT JOIN (

SELECT   
D.RIND,
D.ID_MD,
MR.DENUMIRE, 
SUM(D.COL1) AS COL1,
SUM(D.COL2) AS COL2,
SUM(D.COL3) AS COL3,
SUM(D.COL4) AS COL4,
SUM(D.COL5) AS COL5,
SUM(D.COL6) AS COL6
   
 

FROM

CIS2.VW_DATA_ALL D  
                INNER JOIN CIS2.MD_RIND MR ON MR.ID_MD = D.ID_MD


WHERE
   D.PERIOADA IN (:PERIOADA-1) AND
  
  (D.CUIIO=:CUIIO               ) AND
  (D.CUIIO_VERS=:CUIIO_VERS  OR :CUIIO_VERS = -1   ) AND
  (D.FORM = :FORM               ) AND
  (D.FORM_VERS=:FORM_VERS       ) AND
  (D.CAPITOL=:CAPITOL OR :CAPITOL = - 1           ) AND
  (D.CAPITOL_VERS=:CAPITOL_VERS OR :CAPITOL_VERS = -1 ) AND
  (D.ID_MD=:ID_MD OR :ID_MD = -1               ) AND
  

--   D.CUIIO = 819906 AND 
  
  D.FORM IN (33)  AND
  D.CAPITOL IN (379)
  AND  D.NUM IN (2,3,4)
 
 
GROUP BY 
D.RIND,
D.ID_MD,
MR.DENUMIRE



)  R ON R.RIND = L.RIND AND L.ID_MD = R.ID_MD

GROUP BY 
L.RIND,
R.RIND,
R.ID_MD,
L.ID_MD 


HAVING 

SUM(NVAL(L.COL6)) <  SUM(NVAL(R.COL6))